### ISSUE TITLE
rustfmt.toml?

### ISSUE THREAD

**Issue by dscottboggs** [twitchax/kord#1]
I'm working on a PR for audio file clip support, but my editor is changing some unrelated code for formatting reasons. Do you use a formatter? Could you add your preferred `rustfmt.toml` to the repo?

**Comment by twitchax** [comment]
This is a good suggestion.  However, I haven't found a specific one that I use.  What do you recommend?

**Comment by twitchax** [comment]
Yeah, good point: added!
