### ISSUE TITLE
Should notes and pitches implement `Playable`?

### ISSUE THREAD

**Issue by barafael** [twitchax/kord#10]
I see currently a `Chord` is the only thing implementing the `Playable` trait. Does it fit your vision for the crate for `Note` and `Pitch` to implement `Playable`? In theory, it could be possible to do

```rust
impl<F: HasFrequency> Playable for F { ... }
```

However I think that clashes with the existing implementation of `Playable` for `Chord` - I could not get it to work correctly for some reason.

P.S. more of a breaking change, and just a suggestion: in `Playable::play`, I think it might be more practical to take `std::time::Duration` instead of `f32` as arguments. When I first used this function I needed to dig at the source code/try out empirically to find out what the unit of `length` and `delay` and `fade_in` is.

**Comment by twitchax** [comment]
Yeah, good ideas all around.  I can look into this.
