### ISSUE TITLE
Guess notes/chord from audio in JS

### ISSUE THREAD

**Issue by Seanitzel** [twitchax/kord#5]
Hi!

I can't see any way in the JS API to guess notes from audio, is it possible?

Thanks for this cool lib!

**Comment by twitchax** [comment]
Hello!

Yes, it should be possible.  Since guessing a chord is really just guessing a chord from notes, the API would look like this.

```js
let data = callSomeFunctionToLoadAudioData();
let notes = KordNote.fromAudio(data, lengthInSeconds);
let chords = KordChord.fromNotes(notes);
```
